name: test

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: install Go
      uses: actions/setup-go@master
      with:
        go-version: 1.14.x

    - name: checkout code
      uses: actions/checkout@master

    - name: test
      run: go test ./... -v -cover

  integration-test:
    runs-on: ubuntu-latest
    steps:
    - name: install Go
      uses: actions/setup-go@master
      with:
        go-version: 1.14.x

    - name: checkout code
      uses: actions/checkout@master

    - name: test
      run: test -tags=integration -v
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

