on: [push, pull_request]
name: test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: install Go
      uses: actions/setup-go@master
      with:
        go-version: 1.13

    - name: checkout code
      uses: actions/checkout@master

    - name: test
      run: go test ./... -v -cover


